title: Lichess4545 Statistics
description: Stats for the Lichess4545 online chess leagues
logo: assets/img/elia-pellegrini-Ytb42qw9iQ0-unsplash.jpg
theme: jekyll-theme-cayman
google_analytics: G-Q3CEQ766D1