---
title: "About"
output: distill::distill_article
site: distill::distill_website
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, knitr)
```



### FYI

Some small points to bear in mind when interpreting specific stats or outputs.

- The [4545 match 'story' plots](https://rahulan-c.github.io/lichess4545-stats/current.html) only reflect results at the time they were produced. So for example, if a player gets booted from the league late in a season, they will forfeit all their earlier games, but a 'match story' that was produced before these events won't capture those forfeits...unless it's re-created from scratch.

- There was an issue affecting the data used to compute gambit-related stats and awards. It's now been fixed - improved, even - but as of January 2022, the update has only been applied to all 4545 reports, not LW (yet).


### Planned updates

Some day, these might happen.

- Adding more leagues: ~~Chess960~~, Series, Rapid Battle
- All-time stats
- Team logo gallery
- Opening-related stats
- Endgame-related stats (incl. tablebase positions)
- League trivia


### Contact {#contact}

Please use the form below to provide any comments, suggestions or bug reports.

```{=html}
<form method="post" action="https://forms.un-static.com/forms/c65e8c7acaf8b132767fee1fba923d3d07b959c5">
  <div class="form-group row">
    <label for="name" class="col-4 col-form-label">Name</label>
    <div class="col-8">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-user"></i>
        </div>
        <input id="name" name="name" placeholder="Please enter your name" type="text" required="required" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="email" class="col-4 col-form-label">E-mail address (optional)</label>
    <div class="col-8">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-envelope"></i>
        </div>
        <input id="email" name="email" placeholder="Your e-mail address" type="text" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="message" class="col-4 col-form-label">Message</label>
    <div class="col-8">
      <textarea id="message" name="message" cols="40" rows="10" required="required" class="form-control"></textarea>
    </div>
  </div>
  <div class="form-group row">
    <div class="offset-4 col-8">
      <button name="submit" type="submit" class="button">Send</button>
    </div>
  </div>
</form>
<div align="center">
  <p><small>(Powered by <a rel="nofollow" href="https://un-static.com/">Un-static Forms</a>)</small></p>
</div>
```

