---
title: "Stats by season: LoneWolf"
output: distill::distill_article
site: distill::distill_website
---

Statistical reports on every LoneWolf season, split by section.

```{r}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, knitr)
```


```{r season_reports_tbl}

# Show table with all compiled LW season reports

# LW Open
completed_lwopen <- list.files(path = "reports/", pattern = "^stats_lwopen(.*)\\.html$")
any_lwopen <- ifelse(length(completed_lwopen) > 0, T, F)
if(length(completed_lwopen) > 0){
  completed_lwopen <- completed_lwopen %>% 
    str_remove_all("stats_lwopen_s") %>% 
    str_remove_all("\\.html") %>% 
    sort(decreasing = T) %>% 
    paste0("[Season ", ., "]", "(https://rahulan-c.github.io/lichess4545-stats/reports/stats_lwopen_s", ., ".html)")
}

# LW U1800
completed_lwu1800 <- list.files(path = "reports/", pattern = "^stats_lwu1800(.*)\\.html$")
any_lwu1800 <- ifelse(length(completed_lwu1800) > 0, T, F)
if(length(completed_lwu1800) > 0){
 completed_lwu1800 <- completed_lwu1800 %>%  
   str_remove_all("stats_lwu1800_s") %>% 
   str_remove_all("\\.html") %>% 
   sort(decreasing = T) %>% 
   paste0("[Season ", ., "]", "(https://rahulan-c.github.io/lichess4545-stats/reports/stats_lwu1800_s", ., ".html)")
}

# Make sure all completed season vectors are the same length
most_completed <- max(c(length(completed_lwopen), 
                      length(completed_lwu1800)))


if(length(completed_lwopen) < most_completed){
  completed_lwopen <- c(completed_lwopen, rep("", most_completed - length(completed_lwopen)))
}

if(length(completed_lwu1800) < most_completed){
  completed_lwu1800 <- c(completed_lwu1800, rep("", most_completed - length(completed_lwu1800)))
}

# Make league cols empty if there are no completed seasons
if(any_lwopen == F){completed_lwopen <- rep("", most_completed)}
if(any_lwu1800 == F){completed_lwu1800 <- rep("", most_completed)}

# Construct and show table of league reports by season
completed <- tibble("lwopen" = completed_lwopen,
                    "lwu1800" = completed_lwu1800)
knitr::kable(completed, format = "simple", col.names = c("LoneWolf (Open)", "LoneWolf (U1800)"))

```