---
title: "About"
author:
  - name: izzie26
date: "`r Sys.Date()`"
output: distill::distill_article
site: distill::distill_website
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, knitr)
```


### About the site

In early 2021, I started compiling stats for the [Lichess4545 Ledger](https://www.lichess4545.com/team4545/document/ledger-archive/) in the form of round summary dashboards, which were first published in [Ledger #143](https://www.lichess4545.com/team4545/document/ledger-143/). A few months later, I began to expand these round summary stats into standalone season reports, which I first collated and published in August 2021. Thus this site was born.

####  Recent updates

- Added [team logos gallery](https://rahulan-c.github.io/lichess4545-stats/team_logos.html) [Apr '22]
- Published stats for [4545 S29](https://rahulan-c.github.io/lichess4545-stats/reports/stats_4545_s29.html) [Mar '22]
- Published stats for LoneWolf S24 ([Open](https://rahulan-c.github.io/lichess4545-stats/reports/stats_lwopen_s24.html), [U1800](https://rahulan-c.github.io/lichess4545-stats/reports/stats_lwu1800_s24.html))
- Re-designed [homepage](https://rahulan-c.github.io/lichess4545-stats/) [Feb '22]
- Improved live standings 
- Published stats for all [Chess960 seasons](https://rahulan-c.github.io/lichess4545-stats/season_stats.html)
- Published article on the estimated global distribution of league players [Jan '22]
- Published stats for 4545 S28
- Site first published [Aug '21]


#### Future ideas

Things that may be done tomorrow, next week, next month, next year...

- Stats for community leagues, especially **Series** `in progress!` and **Rapid Battle**
- All-time stats, records and trivia `in progress!`
- Stats for the latest rounds `in progress!`
- Stats about league openings
- Stats about endgames reached in league games, à la *100 Endgames You Must Know* `done, just need to publish`


#### Methods/sources

TBC

### Acknowledgements

TBC


### Contact me {#contact}

Please use the form below to provide any comments, suggestions or bug reports.

```{=html}
<form method="post" action="https://forms.un-static.com/forms/c65e8c7acaf8b132767fee1fba923d3d07b959c5">
  <div class="form-group row">
    <label for="name" class="col-4 col-form-label">Name</label>
    <div class="col-8">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-user"></i>
        </div>
        <input id="name" name="name" placeholder="Please enter your name" type="text" required="required" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="email" class="col-4 col-form-label">E-mail address (optional)</label>
    <div class="col-8">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-envelope"></i>
        </div>
        <input id="email" name="email" placeholder="Your e-mail address" type="text" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="message" class="col-4 col-form-label">Message</label>
    <div class="col-8">
      <textarea id="message" name="message" cols="40" rows="10" required="required" class="form-control"></textarea>
    </div>
  </div>
  <div class="form-group row">
    <div class="offset-4 col-8">
      <button name="submit" type="submit" class="button">Send</button>
    </div>
  </div>
</form>
<div align="center">
  <p><small>(Powered by <a rel="nofollow" href="https://un-static.com/">Un-static Forms</a>)</small></p>
</div>
```

