---
title: "Team logo gallery"
description: |
  Much requested, finally here!  
output:
  distill::distill_article
base_url: https://rahulan-c.github.io/lichess4545-stats/
---

I think these are all the team logos that have been made to date - let me know otherwise. They're listed in season order, with the earliest seasons first. I might add season labels later. Click on each image to enlarge.

```{r echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)

# Load all required packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(magick, here, htmltools)
```

<head>

<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.0/css/lightgallery.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.4.1-beta.0/js/lightgallery.min.js"></script>

<!-- lightgallery plugins -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/lg-fullscreen/1.2.1/lg-fullscreen.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lg-thumbnail/1.2.1/lg-thumbnail.min.js"></script>

</head>

```{css}
.column {
  float: left;
  width: 45%;
  margin-left: 1rem;
}
/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
#lightgallery > a > img:hover {
   transform: scale(1.15, 1.15);
   transition: 0.4s ease-in-out;
   cursor: pointer;
}
/* For some reason, icons are not loaded so I choose them myself */
.lg-actions .lg-next {
  content:"\1433"
}
.lg-actions .lg-prev {
  content:"\1438"
}
.lg-toolbar .lg-download {
 content:"\2913"
}
.lg-toolbar .lg-close {
 content:"\00D7"
}
.lg-toolbar .lg-icon {
	background-color: #000;
	border-color: #000;
	border-style: solid;
}
```


```{r, include = FALSE, eval = FALSE}
# Make thumbnails of all full-size team logo images
# NOTE TO FUTURE ME
# If and when this page needs to be rebuilt in the future with more logos, the 
# "eval" knitr chunk argument obviously should be set to TRUE.

img_path <- paste0(here::here(), "/docs/img/team_logos/")

resize_image <- function(image) {
  imFile <- image_read(paste0(img_path, image))
  imFile_resized <- magick::image_resize(imFile, "200")
  magick::image_write(imFile_resized, paste0(img_path, "thumb-", image))
}

list_png <- list.files(img_path)
lapply(list_png, resize_image)
```

```{r, include = FALSE}

img_path <- paste0(here::here(), "/docs/img/team_logos/")
site_path <- "https://raw.githubusercontent.com/rahulan-c/lichess4545-stats/main/docs/img/team_logos/" 

make_gallery_layout <- function() {

  # Get the names of all images
  images <- list.files(img_path)

  # Get the names of all full-size images
  images_full_size <- grep("thumb", images, value = TRUE, invert = TRUE)

  # Get the names of all thumbnails
  images_thumb <- grep("thumb", images, value = TRUE)

  # Create a dataframe where each row is one image (useful for
  # the apply() function)
  images <- data.frame(images_thumb = images_thumb,
                       images_full_size = images_full_size)

  # Create the HTML structure for each image
  tagList(apply(images, 1, function(x) {
      tags$a(
        href = paste0(site_path, x[["images_full_size"]]),
        tags$img(src = paste0(site_path, x[["images_thumb"]]))
      )
  }))

}
```

```{r}
# Create layout
htmltools::withTags(
  div(
    class = "row",
    id = "lightgallery",
    tagList(
      make_gallery_layout()
    )
  )
)

```

<script type="text/javascript">
    lightGallery(document.getElementById('lightgallery'));
</script>