---
title: "Match stories"
description: |
  Visualisations of Lichess4545 matches ([source script](https://github.com/rahulan-c/lichess4545-stats/blob/main/scripts/plot_match_story.R))
output: distill::distill_article
site: distill::distill_website
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, knitr)
```




<!-- ### Round stats -->

<!-- **Under construction - not done yet** -->

<!-- Yes, round summary stats are coming. What you see here is just work in progress. Best to ignore for now.  -->

```{r round_stats_table, eval = FALSE}
# Compile all round stats reports into a single table

# First, identify all compiled round stats
reports_path <- paste0(here::here(), "/docs/")
round_reports <- list.files(path = reports_path, pattern = "^round_stats_(.*)\\.html$")
reports_md <- paste0("[", round_reports, "]",
                       "(", round_reports, ")")
reports_md <- str_c(reports_md, collapse = ", ")

```

### Season 42 (Nov 2024 - Jan 2025)

[R1](reports/stories/s42_r1_allmatches.pdf) | [R2](reports/stories/s42_r2_allmatches.pdf) | [R3](reports/stories/s42_r3_allmatches.pdf) | [R4](reports/stories/s42_r4_allmatches.pdf) | [R5](reports/stories/s42_r5_allmatches.pdf) | [R6](reports/stories/s42_r6_allmatches.pdf) | [R7](reports/stories/s42_r7_allmatches.pdf) | [R8](reports/stories/s42_r8_allmatches.pdf)

### Season 41 (Sep 2024 - Nov 2024)

[R1](reports/stories/s41_r1_allmatches.pdf) | [R2](reports/stories/s41_r2_allmatches.pdf) | [R3](reports/stories/s41_r3_allmatches.pdf) | [R4](reports/stories/s41_r4_allmatches.pdf) | [R5](reports/stories/s41_r5_allmatches.pdf) | [R6](reports/stories/s41_r6_allmatches.pdf) | [R7](reports/stories/s41_r7_allmatches.pdf) | [R8](reports/stories/s41_r8_allmatches.pdf)

### Season 40 (Jun 2024 - Aug 2024)

[R1](reports/stories/s40_r1_allmatches.pdf) | [R2](reports/stories/s40_r2_allmatches.pdf) | [R3](reports/stories/s40_r3_allmatches.pdf) | [R4](reports/stories/s40_r4_allmatches.pdf) | [R5](reports/stories/s40_r5_allmatches.pdf) | [R6](reports/stories/s40_r6_allmatches.pdf) | [R7](reports/stories/s40_r7_allmatches.pdf) | [R8](reports/stories/s40_r8_allmatches.pdf)

### Season 39 (Apr 2024 - May 2024)

[R1](reports/stories/s39_r1_allmatches.pdf) | [R2](reports/stories/s39_r2_allmatches.pdf) | [R3](reports/stories/s39_r3_allmatches.pdf) | [R4](reports/stories/s39_r4_allmatches.pdf) | [R5](reports/stories/s39_r5_allmatches.pdf) | [R6](reports/stories/s39_r6_allmatches.pdf) | [R7](reports/stories/s39_r7_allmatches.pdf) | [R8](reports/stories/s39_r8_allmatches.pdf)

### Season 38 (Jan 2024 - Mar 2024)

[R1](reports/stories/s38_r1_allmatches.pdf) | [R2](reports/stories/s38_r2_allmatches.pdf) | [R3](reports/stories/s38_r3_allmatches.pdf) | [R4](reports/stories/s38_r4_allmatches.pdf) | [R5](reports/stories/s38_r5_allmatches.pdf) | [R6](reports/stories/s38_r6_allmatches.pdf) | [R7](reports/stories/s38_r7_allmatches.pdf) | [R8](reports/stories/s38_r8_allmatches.pdf)

### Season 37 (Oct 2023 - Dec 2023)

[R1](reports/stories/s37_r1_allmatches.pdf) | [R2](reports/stories/s37_r2_allmatches.pdf) | [R3](reports/stories/s37_r3_allmatches.pdf) | [R4](reports/stories/s37_r4_allmatches.pdf) | [R5](reports/stories/s37_r5_allmatches.pdf) | [R6](reports/stories/s37_r6_allmatches.pdf) | [R7](reports/stories/s37_r7_allmatches.pdf) | [R8](reports/stories/s37_r8_allmatches.pdf)

### Season 36 (Aug 2023 - Oct 2023)

[R1](reports/stories/s36_r1_allmatches.pdf) | [R2](reports/stories/s36_r2_allmatches.pdf) | [R3](reports/stories/s36_r3_allmatches.pdf) | [R4](reports/stories/s36_r4_allmatches.pdf) | [R5](reports/stories/s36_r5_allmatches.pdf) | [R6](reports/stories/s36_r6_allmatches.pdf) | [R7](reports/stories/s36_r7_allmatches.pdf) | [R8](reports/stories/s36_r8_allmatches.pdf)

### Season 35 (May 2023 - Jul 2023)

[R1](reports/stories/s35_r1_allmatches.pdf) | [R2](reports/stories/s35_r2_allmatches.pdf) | [R3](reports/stories/s35_r3_allmatches.pdf) | [R4](reports/stories/s35_r4_allmatches.pdf) | [R5](reports/stories/s35_r5_allmatches.pdf) | [R6](reports/stories/s35_r6_allmatches.pdf) | [R7](reports/stories/s35_r7_allmatches.pdf) | [R8](reports/stories/s35_r8_allmatches.pdf)


### Season 34 (Feb 2023 - Apr 2023)

[R1](reports/stories/s34_r1_allmatches.pdf) | [R2](reports/stories/s34_r2_allmatches.pdf) | [R3](reports/stories/s34_r3_allmatches.pdf) | [R4](reports/stories/s34_r4_allmatches.pdf) | [R5](reports/stories/s34_r5_allmatches.pdf) | [R6](reports/stories/s34_r6_allmatches.pdf) | [R7](reports/stories/s34_r7_allmatches.pdf) | [R8](reports/stories/s34_r8_allmatches.pdf)

### Season 33 (Dec 2022 - Jan 2023)

[R1](reports/stories/s33_r1_allmatches.pdf) | [R2](reports/stories/s33_r2_allmatches.pdf) | [R3](reports/stories/s33_r3_allmatches.pdf) | [R4](reports/stories/s33_r4_allmatches.pdf) | [R5](reports/stories/s33_r5_allmatches.pdf) | [R6](reports/stories/s33_r6_allmatches.pdf) | [R7](reports/stories/s33_r7_allmatches.pdf) | [R8](reports/stories/s33_r8_allmatches.pdf)

### Season 32 (Sep 2022 - Nov 2022)

[R1](reports/stories/s32_r1_allmatches.pdf) | [R2](reports/stories/s32_r2_allmatches.pdf) | [R3](reports/stories/s32_r3_allmatches.pdf) | [R4](reports/stories/s32_r4_allmatches.pdf) | [R5](reports/stories/s32_r5_allmatches.pdf) | [R6](reports/stories/s32_r6_allmatches.pdf) | [R7](reports/stories/s32_r7_allmatches.pdf) | [R8](reports/stories/s32_r8_allmatches.pdf)

### Season 31 (Jul 2022 - Aug 2022)

[R1](reports/stories/s31_r1_allmatches.pdf) | [R2](reports/stories/s31_r2_allmatches.pdf) | [R3](reports/stories/s31_r3_allmatches.pdf) | [R4](reports/stories/s31_r4_allmatches.pdf) | [R5](reports/stories/s31_r5_allmatches.pdf) | [R6](reports/stories/s31_r6_allmatches.pdf) | [R7](reports/stories/s31_r7_allmatches.pdf) | [R8](reports/stories/s31_r8_allmatches.pdf)


### Season 30 (Apr 2022 - Jun 2022)

[R1](reports/stories/s30_r1_allmatches.pdf) | [R2](reports/stories/s30_r2_allmatches.pdf) | [R3](reports/stories/s30_r3_allmatches.pdf) | R4 | [R5](reports/stories/s30_r5_allmatches.pdf) | [R6](reports/stories/s30_r6_allmatches.pdf) | [R7](reports/stories/s30_r7_allmatches.pdf) | [R8](reports/stories/s30_r8_allmatches.pdf)

### Season 29 (Jan 2022 - Mar 2022)

[R1](reports/stories/s29_r1_allmatches.pdf) | [R2](reports/stories/s29_r2_allmatches.pdf) | [R3](reports/stories/s29_r3_allmatches.pdf) |
[R4](reports/stories/s29_r4_allmatches.pdf) | [R5](reports/stories/s29_r5_allmatches.pdf) | [R6](reports/stories/s29_r6_allmatches.pdf) |
[R7](reports/stories/s29_r7_allmatches.pdf) | [R8](reports/stories/s29_r8_allmatches.pdf)

### Season 28 (Nov 2021 - Jan 2022)

[R1](reports/stories/s28_r1_allmatches.pdf) | [R2](reports/stories/s28_r2_allmatches.pdf) | [R3](reports/stories/s28_r3_allmatches.pdf) | 
[R4](reports/stories/s28_r4_allmatches.pdf) | [R5](reports/stories/s28_r5_allmatches.pdf) | [R6](reports/stories/s28_r6_allmatches.pdf) | [R7](reports/stories/s28_r7_allmatches.pdf) | [R8](reports/stories/s28_r8_allmatches.pdf)

### Season 27 (Aug 2021 - Oct 2021)

[R1](reports/stories/s27_r1_allmatches.pdf) | [R2](reports/stories/s27_r2_allmatches.pdf) | [R3](reports/stories/s27_r3_allmatches.pdf) | [R4](reports/stories/s27_r4_allmatches.pdf) | [R5](reports/stories/s27_r5_allmatches.pdf) | [R6](reports/stories/s27_r6_allmatches.pdf) | [R7](reports/stories/s27_r7_allmatches.pdf) | [R8](reports/stories/s27_r8_allmatches.pdf)

<!-- #### Sandbox -->

<!-- This is me testing a different (cleverer) way to compile and present links to match story plots. Although granted, it doesn't look so clever now.  -->

```{r, eval=FALSE}
# Show all produced match story plots within /docs/reports/stories
# Only show files ending in "allmatches.pdf"

story_paths <- list.files(path = paste0(here::here(), "/docs/reports/stories/"), 
                            pattern = "^(.*)_allmatches\\.pdf$")

story_labels <- story_paths %>% str_remove_all("_allmatches\\.pdf")

story_labels_md <- glue::glue(
  "[{story_labels}](https://rahulan-c.github.io/lichess4545-stats/reports/stories/{story_paths})"
)

story_seasons <- story_labels %>% 
  str_remove_all("_r.*$") %>% 
  str_remove_all("s") %>% 
  as.integer()

story_rounds <- story_labels %>% 
  str_remove_all("^s\\d+_r") %>% 
  as.integer

story_tbl <- tibble::tibble(
  "round_story" = story_labels_md
)

knitr::kable(story_tbl, format = "simple", 
             col.names = c("Season/Round"))

```