---
output:
  html_document:
    css: theme.css
    theme: flatly
    dev: svglite
    toc: yes
    toc_depth: 4
    toc_float: true
    includes:
      in_header: head-custom-google-analytics.html
    self-contained: FALSE
title: "Awards search"
site: distill::distill_website
---



```{r packages_initial_opts, include = FALSE}
# Set default R chunk options for Rmd file
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load all required packages, incl. for functions
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, knitr, rio, kableExtra, gghighlight, data.table,
               ggrepel, ggridges, reactable, htmltools, httr, jsonlite, xml2, 
               rvest, ndjson, reshape2, utf8, lubridate, tictoc, cowplot, 
               tippy)

# Define custom default reactable theme for tables
options(reactable.theme = reactableTheme(
    borderColor = "#dfe2e5",
    stripedColor = "#f6f8fa",
    highlightColor = "#f0f5f9",
    cellPadding = "8px 12px",
    searchInputStyle = list(width = "100%"),
    headerStyle = list(
      "&:hover[aria-sort]" = list(background = "hsl(0, 0%, 96%)"),
      "&[aria-sort='ascending'], &[aria-sort='descending']" = list(background = "hsl(0, 0%, 96%)"),
      borderColor = "#555"
    )
  )
)

```

> Search through all the award winners and details in published season reports.   

[Return to home page](https://rahulan-c.github.io/lichess4545-stats/)


```{r}
# Crawl over the other reports and present all winners in one table

# Extract all links from season reports table on homepage
homepage_url <- "https://rahulan-c.github.io/lichess4545-stats/"
season_reports <- read_html(homepage_url) %>% 
  html_nodes("table") %>% 
  html_nodes("tr") %>% 
  html_nodes("a") %>%
  html_attr("href")

# Now loop through all reports and extract award winners/details
all_awards <- list(rep(NA, length(season_reports)))
for(s in seq(1:length(season_reports))){
  url <- season_reports[s]
  league <- ifelse(str_detect(url, "stats_4545"), 
                   "4545", 
                   ifelse(str_detect(url, "stats_lwopen"), 
                          "LW Open", 
                          ifelse(str_detect(url, "stats_lwu1800"), 
                                 "LW U1800", 
                                 ifelse(str_detect(url, "stats_chess960"),
                                        "Chess960",
                                        ""))))
  
  season <- as.integer(str_extract(url, "(?<=_s)\\d+"))
  
  xml_child_number <- ifelse(league == "4545", 
                             ifelse(season %in% c(2:28),
                                    4,
                                    5),
                             ifelse(league == "LW Open",
                                    ifelse(season %in% c(10, 13, 22, 23),
                                           4,
                                           5),
                                    ifelse(league == "LW U1800",
                                           ifelse(season %in% c(11, 13, 22, 23),
                                                  4,
                                                  5),
                                           ifelse(league == "Chess960",
                                                  ifelse(season %in% c(2:18),
                                                         4,
                                                         5)))))
  
  awards <- read_html(url) %>%
    rvest::html_element("#awards") %>% 
    xml_child(xml_child_number) %>% 
    html_text2() %>% 
    parse_json()
  
  awards_tidy <- as_tibble(awards$x$tag$attribs$data) %>%
    mutate(League = league, Season = season) %>% 
    select(-c(Image)) %>% 
    select(League, Season, Award, Winner, Details) %>% 
    # Flatten list to columns, turning NULL values to NAs
    mutate(Award = Award %>% lapply(function(x) ifelse(is.null(x), NA, x)) %>% purrr::flatten() %>% unlist(),
           Winner = Winner %>% lapply(function(x) ifelse(is.null(x), NA, x)) %>% purrr::flatten() %>% unlist(),
           Details = Details %>% lapply(function(x) ifelse(is.null(x), NA, x)) %>% purrr::flatten() %>% unlist())
  
  all_awards[[s]] <- awards_tidy
  cli::cli_inform("{league} S{season} done")
  Sys.sleep(0.2)
}

# Combine everything into a single data frame
awards <- data.table::rbindlist(all_awards)

# Tidy the data
awards <- awards %>% 
  filter(Winner != "") %>% # exclude non-awarded awards
  filter(!(Award %in% c("Egalitarian Award", "Team Accuracy", "Radjabov Award"))) %>% # exclude team-based awards
  arrange(Winner) %>% 
  mutate(league_season = paste0(League, " S", Season)) %>% 
  select(Winner, Award, Details, league_season)

rm(all_awards, awards_tidy)

# Show final table
reactable(awards,
          pagination = TRUE, 
          fullWidth = TRUE,
          resizable = TRUE,
          searchable = TRUE,
          columns = list(
            Winner = colDef(name = "Player", align = "left", minWidth = 200),
            Award = colDef(name = "Award", minWidth = 150),
            Details = colDef(name = "Details", minWidth = 250),
            league_season = colDef(name = "League / Season", minWidth = 150)
            )
)
```
