---
title: "About"
output: distill::distill_article
site: distill::distill_website
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, knitr)
```



### FYIs

- [Feb 2022] I still need to update most of the existing LoneWolf season reports to reflect necessary revisions to the computation of gambit-related stats and awards. These changes have already been reflected in all 4545 reports (except S1), and aren't applicable to the Chess960 league. 



### Recent updates

#### February 2022

- Published the latest stats for the LoneWolf league (season 24)
- Re-designed the homepage

#### January 2022

- Improved live standings page; still only works for 4545, and still not properly automated
- Published season stats and awards for the Chess960 league
- Published article on where league players come from, using the flags they choose to show on their Lichess profiles
- Published the latest stats for the 4545 Team league (season 28)

#### August 2021

- Site first published


### Future ideas

Consider this a form of motivation through public commitment. In other words, these might be done next week, next month, next year...or never.

- Adding new leagues: ~~Chess960~~ Series, Rapid Battle (yes, I know I've been promising these for ages)
- Reporting all-time stats, records and trivia
- Team logo gallery
- Stats about league openings
- Stats about endgames reached in league games, à la *100 Endgames You Must Know*
- Stats about 7-piece tablebase positions reached in league games...and their outcomes

#### Stupidly ambitious ideas

- A world map showing connections between players (a version for live games definitely can't be done, but even a static version based on historical data is ambitious and magnificently pointless)


### About the site

[to be completed]

#### Methods/sources

[ditto]


### Contact me {#contact}

Please use the form below to provide any comments, suggestions or bug reports.

```{=html}
<form method="post" action="https://forms.un-static.com/forms/c65e8c7acaf8b132767fee1fba923d3d07b959c5">
  <div class="form-group row">
    <label for="name" class="col-4 col-form-label">Name</label>
    <div class="col-8">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-user"></i>
        </div>
        <input id="name" name="name" placeholder="Please enter your name" type="text" required="required" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="email" class="col-4 col-form-label">E-mail address (optional)</label>
    <div class="col-8">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-envelope"></i>
        </div>
        <input id="email" name="email" placeholder="Your e-mail address" type="text" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="message" class="col-4 col-form-label">Message</label>
    <div class="col-8">
      <textarea id="message" name="message" cols="40" rows="10" required="required" class="form-control"></textarea>
    </div>
  </div>
  <div class="form-group row">
    <div class="offset-4 col-8">
      <button name="submit" type="submit" class="button">Send</button>
    </div>
  </div>
</form>
<div align="center">
  <p><small>(Powered by <a rel="nofollow" href="https://un-static.com/">Un-static Forms</a>)</small></p>
</div>
```

